# Generated by Django 3.2.13 on 2022-11-01 07:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='tag',
        ),
        migrations.AlterField(
            model_name='comment',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '커피맛'), (2, '인테리어'), (3, '디저트')], max_length=5),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
