# Generated by Django 3.2.13 on 2022-11-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20221103_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='lastorder',
        ),
    ]
