# Generated by Django 3.2.13 on 2022-11-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20221101_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.cafe'),
            preserve_default=False,
        ),
    ]
