# Generated by Django 3.2.13 on 2022-11-03 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20221103_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarksuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(related_name='likeuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
