# Generated by Django 3.2.13 on 2022-11-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20221103_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='emotion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cafe',
            name='hip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cafe',
            name='love',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cafe',
            name='sight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cafe',
            name='study',
            field=models.IntegerField(default=0),
        ),
    ]
