# Generated by Django 3.2.13 on 2022-11-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='dessert',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cafe',
            name='interior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cafe',
            name='taste',
            field=models.IntegerField(default=0),
        ),
    ]
