# Generated by Django 3.2.13 on 2022-11-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20221102_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cafe',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
