# Generated by Django 3.2.13 on 2022-11-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dessert',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='interior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='taste',
            field=models.IntegerField(default=0),
        ),
    ]
