# Generated by Django 3.2.13 on 2022-11-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221104_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emotion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='love',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='study',
            field=models.IntegerField(default=0),
        ),
    ]
