# Generated by Django 3.2.13 on 2022-11-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('accounts', '0002_auto_20221104_0917'),
=======
        ('accounts', '0002_auto_20221104_1002'),
>>>>>>> 0daf347e8c9cd59c53650283ce976957223f6b32
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emotion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='love',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='study',
            field=models.IntegerField(default=0),
        ),
    ]
