# Generated by Django 3.2.13 on 2022-11-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221104_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='선영', max_length=10),
            preserve_default=False,
        ),
    ]
